version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - CELERY_BROKER_URL=amqps://wfnozibh:4T_jdMaK65ElpLne0WeKkrzWW0v3BARP@possum.lmq.cloudamqp.com/wfnozibh
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - CELERY_BROKER_URL=amqps://wfnozibh:4T_jdMaK65ElpLne0WeKkrzWW0v3BARP@possum.lmq.cloudamqp.com/wfnozibh
