AWSTemplateFormatVersion: '2010-09-09'
Description: 'Celery Worker Stack'

Resources:
  WorkerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Celery worker
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5671
          ToPort: 5671
          CidrIp: 0.0.0.0/0

  WorkerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0735c191cf914754d  # Amazon Linux 2 AMI in us-west-2
      SecurityGroups:
        - !Ref WorkerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y docker
          service docker start
          usermod -a -G docker ec2-user
          docker run -d \
            --name text-processor-worker \
            --restart unless-stopped \
            ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/text-processor-worker:latest

Outputs:
  WorkerInstanceId:
    Description: ID of the worker EC2 instance
    Value: !Ref WorkerInstance
  WorkerPublicDNS:
    Description: Public DNS of the worker EC2 instance
    Value: !GetAtt WorkerInstance.PublicDnsName
